name: flutter_pay_u_money_example
description: Demonstrates how to use the flutter_pay_u_money plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_pay_u_money:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:

  uses-material-design: true
